name: Build IPA

on:
 workflow_dispatch:
  inputs:
   file:
    required: true

jobs:

 build:

  runs-on: macos-latest

  steps:

  - uses: actions/checkout@v4

  - name: Download ZIP
    run: |
      curl -L ${{ secrets.SERVER }}/uploads/${{ github.event.inputs.file }} -o app.zip

  - name: Unzip
    run: |
      unzip app.zip -d src

  - name: Detect Scheme
    run: |
      cd src
      SCHEME=$(xcodebuild -list | grep Scheme | tail -n +2 | head -n 1 | xargs)
      echo "SCHEME=$SCHEME" >> $GITHUB_ENV

  - name: Build
    run: |
      cd src
      xcodebuild -scheme $SCHEME -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO

  - name: Package IPA
    run: |
      mkdir Payload
      cp -r src/build/Release-iphoneos/*.app Payload/
      zip -r app.ipa Payload

  - name: Upload
    run: |
      curl -X POST -F file=@app.ipa ${{ secrets.SERVER }}/uploadIPA
